/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as DecksIdRouteImport } from './routes/decks.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdRoute = DecksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecksRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/store': typeof StoreRoute
  '/decks/$id': typeof DecksIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/store': typeof StoreRoute
  '/decks/$id': typeof DecksIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/store': typeof StoreRoute
  '/decks/$id': typeof DecksIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/collection'
    | '/decks'
    | '/locker'
    | '/login'
    | '/match'
    | '/missions'
    | '/play'
    | '/setup'
    | '/store'
    | '/decks/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/collection'
    | '/decks'
    | '/locker'
    | '/login'
    | '/match'
    | '/missions'
    | '/play'
    | '/setup'
    | '/store'
    | '/decks/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/collection'
    | '/decks'
    | '/locker'
    | '/login'
    | '/match'
    | '/missions'
    | '/play'
    | '/setup'
    | '/store'
    | '/decks/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  CollectionRoute: typeof CollectionRoute
  DecksRoute: typeof DecksRouteWithChildren
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  MissionsRoute: typeof MissionsRoute
  PlayRoute: typeof PlayRoute
  SetupRoute: typeof SetupRoute
  StoreRoute: typeof StoreRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$id': {
      id: '/decks/$id'
      path: '/$id'
      fullPath: '/decks/$id'
      preLoaderRoute: typeof DecksIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DecksRouteChildren {
  DecksIdRoute: typeof DecksIdRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksIdRoute: DecksIdRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRouteWithChildren,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  MissionsRoute: MissionsRoute,
  PlayRoute: PlayRoute,
  SetupRoute: SetupRoute,
  StoreRoute: StoreRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
